# Generated by Django 5.0.4 on 2024-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
